### ISSUE TITLE
Errors because no user 'Pi'

### ISSUE THREAD

**Issue by mendip-defender** [PhilippCo/meas_rpi#2]
Recently there has been a change for the user not to default to Pi, so some of your scripts fail because they refer to files being saved in folders that don't exist.

**Comment by PhilippCo** [comment]
yes, you're absolutely right, but it is still possible to use the username 'pi'

Do you think it is a real problem?

**Comment by mendip-defender** [comment]
Not really. I just had two attempts fail because I didn't sport it at first. Now on the 3rd attempt. SciPy is being a pain though, I updated Pip and that allowed the current version to install but now it complains Gfortran isn't installed.

**Comment by PhilippCo** [comment]
I'm currently running a test for SciPy with modified install.sh

I will add a comment, that one needs the username pi and close this issues here
