### ISSUE TITLE
/boot/config.txt move to /boot/firmware/config.txt

### ISSUE THREAD

**Issue by ghost** [PhilippCo/meas_rpi#5]
after upgrade, /boot/config.txt has move to /boot/firmware/config.txt, so upgrade command need some change. my device PI 3B.
![未命名1707026402](https://github.com/PhilippCo/meas_rpi/assets/39869575/c56b104c-d147-4fac-9614-d3a701aa480f)

**Comment by PhilippCo** [comment]
Thanks for the hint!!
I changed that
