### ISSUE TITLE
Install scipt fails at gpib install

### ISSUE THREAD

**Issue by mendip-defender** [PhilippCo/meas_rpi#6]
![image](https://github.com/user-attachments/assets/c85be1ef-fad5-4e12-8417-b3c8a636d153)

Exits the install script at,
`gpib_firmware-2008-08-10/hp_82350a/agilent_82350a.bin
groupadd: group 'gpib' already exists
adduser: The user `pi' is already a member of `gpib'.
SUBSYSTEM=="usb", MODE="0666", GROUP="gpib"
failed to open device file '/dev/gpib0'
main: No such file or directory`

This is on a Pi5 using bookworm 64bit.

**Comment by PhilippCo** [comment]
Thanks for your hint!
I will have a look into it as soon as possible. Is it a fresh installation?

**Comment by mendip-defender** [comment]
Brand new Pi5 with a fresh install. Jupyter is running after a reboot but I have not hooked up to a GPIB to test that part yet.

**Comment by PhilippCo** [comment]
Same behaviour here with a Pi4

Seems that I already put an "exit" into the script right at that point

**Comment by PhilippCo** [comment]
![image](https://github.com/user-attachments/assets/5e741f2e-4687-4768-9322-501a09a24ae2)
After connecting a USB-to-GPIB Interface the error message disappears

**Comment by PhilippCo** [comment]
![image](https://github.com/user-attachments/assets/8cebdfbd-a1d5-4618-a20c-34c020870282)

After a couple of modifications it works again on a Pi4
